---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: snacka-kod
  namespace: flux-system
spec:
  interval: 30m0s
  path: ./snacka-kod
  prune: true
  retryInterval: 2m0s
  sourceRef:
    kind: GitRepository
    name: microservice-configurations
  targetNamespace: default
  timeout: 3m0s
  wait: true
