name: Maven Package

on:
  push:
    branches: [ "main" ]


jobs:
  call-workflow-passing-data:
    uses: paulopaniniorg/workflows/.github/workflows/build.yml@main
    with:
      project_name: snacka-kod
    secrets: inherit

